### ISSUE TITLE
Plain links are exported with the text "nil"

### ISSUE THREAD

**Issue by CyberShadow** [mmitch/ox-bb#1]
E.g. `https://www.example.com/` gets exported as `[url=https://www.example.com/]nil[/url]`.

**Comment by mmitch** [comment]
Does this work for you?

Thanks for reporting, you are the first user that I know of. I did not yet manage to make any forum posting with this exporter, it's all quite untested so far ;-)

**Comment by CyberShadow** [comment]
Thank you! I used to use https://github.com/levindu/org-ox-bbcode but it stopped working with current Org versions and doesn't seem to be maintained any more.
