### ISSUE TITLE
[list]s predicted, # & == received

### ISSUE THREAD

**Issue by Jonta** [mmitch/ox-bb#4]
Input:

```
* Top item
** Sub-item
```

Output:

```
[b][u]# Top item[/u][/b]

[b][u]== Sub-item[/u][/b]
```
Expected output:
```
[list]
[*]Top item
[list]
[*]Sub-item
[/list]
[/list]
```

**Comment by mmitch** [comment]
Org parses your input as headlines, not as list items.

This behaviour is documented in the Org manual:

> When using ‘\*’ as a bullet, lines must be indented so that they are not interpreted as headlines. Also, when you are hiding leading stars to get a clean outline view, plain list items starting with a star may be hard to distinguish from true headlines. In short: even though ‘\*’ is supported, it may be better to not use it for plain list items.

(source: [Footnote 9 in 2.6 Plain Lists](https://orgmode.org/manual/Plain-Lists.html#FOOT9))

As Org does the parsing of the source document, there is nothing I could do about it.
_ox-bb_ only formats the document tree after it has been parsed by Org.

**Comment by Jonta** [comment]
```
- Top item
  - Sub-item
```
results in
```
[list]
[*]Top item
[list]
[*]Sub-item
[/list]
[/list]
```

Better than nothing, but I still prefer using asterisk-bulletpoints in org

What would be the best way of having my cake and eating it too in this case? =)

**Comment by mmitch** [comment]
You can use indentation like the Org manual says:

```
  * top
    * sub
```
instead of
```
- top
   - sub
```

For everything else you need to contact your Orgmode dealer ;-)
