### ISSUE TITLE
Register in dispatcher

### ISSUE THREAD

**Issue by xeruf** [mmitch/ox-bb#7]
Thanks for the extension! However, it seems it is missing an entry in the export dispatcher.

**Comment by mmitch** [comment]
The registration into the export menu happens here: https://github.com/mmitch/ox-bb/blob/545d2e1547fdc48a5757152d19233effa11d9ee2/ox-bb.el#L104-L108

* Are you sure that ox-bb is loaded correctly?
* Do you have any other extensions that might be registered under `b`?
* Which emacs version are you using?

**Comment by xeruf** [comment]
Nevermind, I forgot to load it correctly :) Thank you!
