### ISSUE TITLE
LINK type 'id' not yet supported

### ISSUE THREAD

**Issue by pierreay** [mmitch/ox-bb#8]
Hello! I'm trying to use this export backend with *Org* documents containing a lots of `id:` internal links. 

However, whatever the value of the `org-export-with-broken-links` variable, I'm getting the following error which stops the export process:

``` *Messages*
ox-bb-link: LINK type ‘id’ not yet supported
```

Is there a way that the exporter only keep the text description but skip the internal link? :)

Thanks!

**Comment by mmitch** [comment]
Doing that should be easy.
Just to be sure, could you give me a minimal example org file containing such a link?

**Comment by pierreay** [comment]
Okay, trying to reproduce the problem with a minimal working example, another problem raised!

Here is the minimal `init.el`:

``` lisp
(setq package-archives
      '(("GNU ELPA"     . "https://elpa.gnu.org/packages/")     ;; FSF maintained GPLv3 only.
        ("NonGNU ELPA"  . "https://elpa.nongnu.org/nongnu/")    ;; FSF maintained GPLv3-compatible only.
        ("MELPA Stable" . "https://stable.melpa.org/packages/") ;; Community-driven stable releases.
        ("MELPA"        . "https://melpa.org/packages/"))       ;; Community-driven rolling releases.
      package-archive-priorities
      '(("MELPA"        . 5)
        ("GNU ELPA"     . 4)
        ("NonGNU ELPA"  . 3)
        ("MELPA Stable" . 2)
        ))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))
 
(use-package ox-bb)

(custom-set-variables
 '(package-selected-packages '(ox-bb)))
```

Here is the minimal Org-mode file `mwe.org`:

``` org
* A heading
:PROPERTIES:
:ID:       25556746-afe1-4559-8481-af68f50dbfde
:END:
```

Trying to export this using `C-c C-e b B`, I get:

``` *Message*
ox-bb-section: Wrong type argument: arrayp, nil
```

And there is no results! :(

**Comment by pierreay** [comment]
This ID property is inserted by creating a link using `org-store-link` when the variable `org-id-link-to-org-use-id` is set to `'create-if-interactive`.

**Comment by mmitch** [comment]
Please test the branch `link-with-id`, it should fix the problem: https://github.com/mmitch/ox-bb/tree/link-with-id

**Comment by pierreay** [comment]
Using the same MWE as above and using the `link-with-id` branch, the `ox-bb-section: Wrong type argumentf: arrayp, nil` error is gone and the export is successful!

Coming back to my very first issue, using the following MWE:

``` org
* A heading
:PROPERTIES:
:ID:       25556746-afe1-4559-8481-af68f50dbfde
:END:

* Second heading

Test text, with link to [[id:25556746-afe1-4559-8481-af68f50dbfde][A heading]].
```

And when using `ox-bb-export-to-bbcode`, I now get the following error:

``` *Messages*
cond: LINK type ‘id’ not yet supported
```

**Comment by mmitch** [comment]
On my system I get `Unknown fuzzy LINK type encountered: ‘id:25556746-afe1-4559-8481-af68f50dbfde’` as an error, so this seems to depend on the Emacs version.
The test pipeline uses different Emacen, so I think I'll figure it out.
I'm on it!

**Comment by mmitch** [comment]
I think that should work, please have a look at the updated `link-with-id` branch.

**Comment by pierreay** [comment]
Thanks, that works well! ;) Btw, I'm using Emacs v30.0.50.

**Comment by mmitch** [comment]
That's interesting:  
Your Emacs 30 showed the same error massage as Emacs 24 and 25 in my CI pipeline,  
while my Emacs 28.2 (Debian stable) showed the other error message, just as Emacs 26 and 27 in my CI pipeline.

I deduct two things from that:
1. it looks like OrgMode has reverted some internal details about property parsing
2. I definitely need to update the Emacs versions in my CI pipeline ;-)

Thanks for reporting the bug and testing it!
